// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Onyx.Services.ProductAPI.Data;

#nullable disable

namespace Onyx.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Onyx.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Colour")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Colour = "Golden Brown",
                            Description = "A crispy and spicy Indian snack filled with mashed potatoes, peas, and aromatic spices.",
                            Name = "Samosa",
                            Price = 15m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            Colour = "Orange",
                            Description = "Marinated paneer cubes grilled to perfection with capsicum and onions, served with mint chutney.",
                            Name = "Paneer Tikka",
                            Price = 13.99m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Colour = "Yellow",
                            Description = "An Indian-style sweet pie with a hint of cardamom, nuts, and saffron, served warm.",
                            Name = "Sweet Pie",
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Colour = "Reddish Brown",
                            Description = "A famous Mumbai street food — spicy mashed vegetables served with buttered pav (bread rolls).",
                            Name = "Pav Bhaji",
                            Price = 15m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Entree",
                            Colour = "Light Brown",
                            Description = "A thin, crispy rice crepe stuffed with spiced mashed potatoes, served with coconut chutney and sambar.",
                            Name = "Masala Dosa",
                            Price = 12.50m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Dessert",
                            Colour = "Dark Brown",
                            Description = "Soft deep-fried milk balls soaked in sugar syrup, flavored with rose water and cardamom.",
                            Name = "Gulab Jamun",
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryName = "Entree",
                            Colour = "Mixed Yellow/Brown",
                            Description = "Aromatic basmati rice cooked with marinated chicken, saffron, and traditional Hyderabadi spices.",
                            Name = "Chicken Biryani",
                            Price = 18.99m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryName = "Dessert",
                            Colour = "White",
                            Description = "Soft and spongy cheese balls soaked in light sugar syrup, a classic Bengali dessert.",
                            Name = "Rasgulla",
                            Price = 6.50m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryName = "Entree",
                            Colour = "Brown",
                            Description = "A North Indian dish with spicy chickpeas (chole) served with deep-fried bread (bhature).",
                            Name = "Chole Bhature",
                            Price = 14.00m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryName = "Appetizer",
                            Colour = "Golden Brown",
                            Description = "Crispy potato patties seasoned with Indian spices, often served with tamarind and mint chutneys.",
                            Name = "Aloo Tikki",
                            Price = 8.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
